Added homepage background change. Closed #3.
TopAcademy2022/simple-to-do-list pull request #16
Opened 2024-04-24 18:16 UTC by Andrey31ts

2024-04-24 18:23 UTC, TopAcademy2022 requested changes

2024-04-24 18:23 UTC, TopAcademy2022 commented on src/index.html
> +					<i class="bi bi-back" ></i>
Revert.

2024-04-24 18:23 UTC, TopAcademy2022 commented on src/index.html
> +
Remove spaces.

2024-04-24 18:23 UTC, TopAcademy2022 commented on src/script.js
> +
Remove space.

2024-04-24 18:23 UTC, TopAcademy2022 commented on src/script.js
> +
Remove spaces.

2024-04-24 18:23 UTC, TopAcademy2022 commented on src/script.js
> +
Remove spaces.

2024-04-24 18:23 UTC, TopAcademy2022 commented on src/script.js
> +	let openImageInput = document.getElementById('file-open-b');
Rename Id.

2024-04-24 18:23 UTC, TopAcademy2022 commented on src/style.css
> +#file-open, #file-open-image, #file-open-b {
Rename id.

2024-04-24 18:23 UTC, TopAcademy2022 commented on src/style.css
> +
Remove space.

2024-04-26 17:33 UTC, TopAcademy2022 requested changes

2024-04-26 17:33 UTC, TopAcademy2022 commented on src/script.js
> +
Remove space.

2024-04-26 17:41 UTC, TopAcademy2022 requested changes

2024-04-26 17:41 UTC, TopAcademy2022 commented on src/index.html
> +
Remove space.

2024-04-29 15:56 UTC, Mi-stik31 approved these changes

2024-05-29 15:50 UTC, closed without merging